---
- fail:
    msg: Please provide all required variables
  when: not gitlab_url or not gitlab_runner_token or not gitlab_runner_description or not gitlab_runner_tag

- name: Ensure python-toml is installed
  pip:
    name: toml
    extra_args: "--user"

- name: Ensure that the runner is not registered already
  script: "src/search-runner.py --config /srv/gitlab-runner/config/config.toml --query \"{{gitlab_runner_description}}\""
  args:
    executable: python
  become: true
  register: script_output

- set_fact:
    runner_exists: "{{ script_output.stdout_lines[0] == 'True' }}"

- name: Ensure gitlab runner is running
  docker_container:
    image: gitlab/gitlab-runner
    name: gitlab-runner
    detach: true
    restart_policy: always
    state: started
    volumes:
    - /srv/gitlab-runner/config:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
  when: not runner_exists

- name: Verify all runners and delete old ones
  docker_container:
    image: gitlab/gitlab-runner
    name: gitlab-runner-verify
    state: started
    #   can only be used with pip docker new version, Cent os does not provide id yet.
    #    auto_remove: true
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
    command: "verify --delete"

- name: Register a new gitlab runner
  docker_container:
    image: gitlab/gitlab-runner
    name: gitlab-runner-register
    state: started
#   can only be used with pip docker new version, Cent os does not provide id yet.
#    auto_remove: true
    volumes:
    - /srv/gitlab-runner/config:/etc/gitlab-runner
    command: "register --non-interactive --executor \"docker\" --docker-image docker:latest --url \"{{gitlab_url}}\" --registration-token \"{{gitlab_runner_token}}\" --description \"{{gitlab_runner_description}}\" --tag-list \"{{gitlab_runner_tag}}\" --locked=\"{{gitlab_runner_locked}}\""
  when: not runner_exists

- name: Ensure the Docker socket is in the Gitlab Runner config section as volume definied
  lineinfile:
    line: '    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]'
    regexp: volumes
    path: /srv/gitlab-runner/config/config.toml
  become: true
  when: not runner_exists
