---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python for Ansible
      raw: yum -y install epel-release python python-pip
      become: true

    - name: Ensure docker-py is installed
      pip:
        name: "{{item}}"
      become: true
      loop:
        - setuptools
        - docker

    - name: Ensure docker is installed
      import_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - vagrant
      become: true

