---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python for Ansible
      raw: "yum -y install epel-release python && yum -y install python-pip"
      become: true
      register: out

    - debug:
        var: out

    - name: Ensure docker-py is installed
      pip:
        name: "{{item}}"
      become: true
      loop:
        - docker

    - name: Ensure docker is installed
      import_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - vagrant
      become: true
